name: C/C++ CI

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: macos-11

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        modules: 'qtcharts qtscript qtwebengine'
        
    - uses: actions/checkout@v3
    - name: qmake
      run: qmake -makefile CaptureStream2-extra.pro
    - name: make
      run: make
      
    - name: Make CaptureStream0 executable
      run: sudo chmod -R 755 ./CaptureStream2-extra.app
  
    - uses: actions/upload-artifact@v3
      with:
        name: CaptureStream2-extra
        path: ./

