name: test


on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: install qt static
      uses: orestonce/install-qt-static@v0.4.3
      with:
        version: Qt6.5.3-Windows-x86_64-MinGW13.2.0-ucrt-staticFull-20240527

    - name: build  
      run: |
        cd ../../
        cmake -S ./ -B ./
        make
      
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-Rad
        path: ./

