name: test


on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: install qt static
      uses: orestonce/install-qt-static@v0.4.3
      with:
        version: Qt6.5.3-Windows-x86_64-MinGW13.2.0-ucrt-staticFull-20240527
   
    - name: build  
      run: |
        cd D:/a/CaptureStream2-Rad/
        cmake -S ./ -B ./ && mingw32-make release

    - name: Tar files
      run: tar cvf CaptureStream2-Rad.tar ./
      
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-Rad
        path: CaptureStream2-Rad.tar

