name: test2


on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: install qt static
      uses: anthepro/install-qt-static@v1
      with:
        version: 6.5.2
        configure-args: -opensource -opengl desktop
        submodules: qtbase,qtshadertools,qtdeclarative
   
    - uses: actions/checkout@v3
    - name: build  
      run: |
        qmake -makefile CaptureStream2-Rad.pro
        make
 
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-Rad
        path: ./

