name: test


on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: install qt static
      uses: orestonce/install-qt-static@v0.4.3
      with:
        version: Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104
   
    - name: build  
      run: |
        qmake CaptureStream2-Rad.pro && mingw32-make release

    - name: Tar files
      run: tar cvf CaptureStream2-Rad.tar ./
      
    - uses: actions/upload-artifact@v4
      with:
        name: CaptureStream2-Rad
        path: CaptureStream2-Rad.tar

