name: test

on:
  workflow_dispatch:
      branches: [ master ]
      

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: install qt static
      uses: orestonce/install-qt-static@v0.4.3
      with:
      version: Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104
    
    - name: build
    run: |
      cd image2pdf-qt && qmake && mingw32-make release && cd ..
      dir image2pdf-qt\release\image2pdf-qt.exe

